version: '3.8'

services:
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
#      - /app/node_modules
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"   
    environment:
      - NODE_ENV=development