version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  product-service:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - ./services/product-service/.env

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    env_file:
      - ./services/auth-service/.env

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    env_file:
      - ./services/order-service/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - auth-service
      - order-service
    env_file:
      - ./frontend/.env

volumes:
  mongodb_data:
