version: "3.9"
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: frontend
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
    env_file:
      - ./frontend/.env.production
    depends_on:
      product-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      order-service:
        condition: service_healthy

  product-service:
    build: 
      context: ./services/product-service
      dockerfile: Dockerfile
      target: production
    container_name: product-service
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - ./services/product-service/.env.production
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"] 
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  auth-service:
    build: 
      context: ./services/auth-service
      dockerfile: Dockerfile
      target: production
    container_name: auth-service
    ports:
      - "3001:3001"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - ./services/auth-service/.env.production
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/api/health"] 
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  order-service:
    build: 
      context: ./services/order-service
      dockerfile: Dockerfile
      target: production
    container_name: order-service
    ports:
      - "3002:3002"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - ./services/order-service/.env.production
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3002/api/health"] 
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  frontend:
  backend:
volumes:
  mongodb_data: