version: '3.8'

services:
  mongo:
      image: mongo:6
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
  order-service:
    build: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  mongo_data: